### PR TITLE
ignore py2 errors

### PR DESCRIPTION
**Pull request by goneri**
- ignore all the errors with pre-3.8 Python
- add a script to refresh the ignores files easily

### CODE REVIEW

**Comment by tremble** [comment]
Can we use the --skip-test option instead of mass-adding ignore entries?

**Comment by goneri** [comment]
> Can we use the --skip-test option instead of mass-adding ignore entries?

We cannot use `--skip-test`, the option does not accept things like `compile-3.7!skip`. It can just fully turn off the test. In addition, we don't control the ansible-test configuration of AutomationHub. So it will still test againt py27.

**Comment by tremble** [comment]
@goneri Then FWIW this is probably the right change to make but we should talk to @mattclay about a better long term solution for disabling/reconfiguring ansible-test

**Comment by tremble** [comment]
https://github.com/openstack/ansible-collections-openstack/blob/master/tools/run-ansible-sanity.sh#L28

I don't quite get why we care about not totally turning off the Python 2.6/2.7/3.5 tests, but I'll not push here.

**Comment by jillr** [comment]
@tremble I would also prefer to avoid hundreds of ignores (community.aws is going to be "fun") but in the immediate term we can't keep blocking CI.  :(

**Comment by goneri** [comment]
> https://github.com/openstack/ansible-collections-openstack/blob/master/tools/run-ansible-sanity.sh#L28
> 
> I don't quite get why we care about not totally turning off the Python 2.6/2.7/3.5 tests, but I'll not push here.

They test with Python 3.6 only. This is another approach that we can take, but we will still need to have the ignore files at some point because of AutomationHub.

**Review by jillr — APPROVED** [review]
lgtm when #370 passes (contains 3-only changes)

**Comment by goneri** [comment]
@tremble I've open this a while ago: https://github.com/ansible/ansible/issues/74398. @mattclay has since pushed a new feature that give the ability to disable a Python version. But it won't be backported.

**Comment by jillr** [comment]
370 sanity is passing now (the integration failures are unrelated).  thanks @goneri!

**Pull request merged**
