### PR TITLE
increase concurrency of ec2_instance tests

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Looks like the ec2_instance tests were getting stomped on by aws_terminator, try bumping up the concurrency and see if things improve

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_instance

##### ADDITIONAL INFORMATION

https://dashboard.zuul.ansible.com/t/ansible/builds?job_name=ansible-test-cloud-integration-aws-py36_0&project=ansible-collections%2Famazon.aws&change=495

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by jillr — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
4th test in a row passed.  I'm going to gate and call this good.

**Pull request merged**
