### PR TITLE
Add PSF-license.txt file

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
plugins/module_utils/_version.py mentions PSF-license.txt, which doesn't exist yet.

Please make sure to create new releases with this ASAP.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
licenses

### CODE REVIEW

**Review by tremble — APPROVED** [review]
Thanks for catching this one @felixfontein

**Comment by felixfontein** [comment]
@tremble you have to thank @gotmax23 for catching this :)

**Review by markuman — APPROVED** [review]

**Review by Akasurde — APPROVED** [review]

**Review by alinabuzachis — APPROVED** [review]

**Comment by felixfontein** [comment]
I created a manual backport to stable-3 in #813.

**Comment by felixfontein** [comment]
@tremble @markuman @Akasurde @alinabuzachis thanks for reviewing and helping getting this and the backport merged! :)

**Pull request merged**
