### PR TITLE
DNM Migrate ec2_transit_gateway module and tests

### PR DESCRIPTION
**Pull request by mandar242**
##### SUMMARY

DNM Migrate ec2_transit_gateway modules and tests
Refer : https://issues.redhat.com/browse/ACA-1877

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by GomathiselviS — COMMENTED** [review]
Please modify the FQCN in tests to point to amazon.aws modules

**Review by alinabuzachis — APPROVED** [review]
LGTM! Linters should be fixed.

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Pull request merged**
