### PR TITLE
Test cleanup

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

- Update FQCN of modules that moved to amazon.aws
- Remove explicit call to ``collections`` from defaults stanza, now we're using FQCNs we don't need to pull it in.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

tests/integration/targets

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by tremble** [comment]
regate

**Pull request merged**
