### PR TITLE
Prep amazon.aws 7.6.0 release

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Prep amazon.aws 7.6.0 release. Release date: 2024-05-07

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by abikouo — APPROVED** [review]

**Review by tremble — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by tremble** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Pull request merged**
