### PR TITLE
Migrate rds_instance* modules and tests

### PR DESCRIPTION
**Pull request by alinabuzachis**
Depends-On: https://github.com/ansible/zuul-config/pull/443

Migrate rds_instance* modules and tests

### CODE REVIEW

**Review by jillr — APPROVED** [review]

**Review by gravesm — APPROVED** [review]

**Comment by alinabuzachis** [comment]
regate

**Review by abikouo — APPROVED** [review]

**Comment by alinabuzachis** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Pull request merged**
