### PR TITLE
Fix refresh_ignore_files script

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt
tests/sanity/refresh_ignore_files

### CODE REVIEW

**Comment by goneri** [comment]
Hi @Akasurde,

What do you think if we move this script somewhere else? This way we would be able to maintain all the these copies at a single place.

**Comment by jillr** [comment]
@goneri  I was just thinking today it might be nice to have a place to keep utility scripts like the module migration script too. +1

**Comment by goneri** [comment]
recheck

**Comment by tremble** [comment]
Rather than spamming the ignore files we can use #447 and ansible/ansible-zuul-jobs#1028

**Comment by tremble** [comment]
This change is now moot as a result of #447 (and https://github.com/ansible/ansible-zuul-jobs/pull/1028)

**Pull request closed without merging**
