### PR TITLE
DNM - testing network-ee jobs

### PR DESCRIPTION
**Pull request by pabelanger**
Depends-On: https://github.com/ansible/network-ee/pull/105
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1046
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by goneri** [comment]
@pabelanger can we close this?

**Comment by pabelanger** [comment]
I can work on it monday, I'd like to add those jobs here still

**Comment by jillr** [comment]
@pabelanger Should we understand from the closed linked PR that amazon.aws does not yet have EE testing?  Is this something I need to open some sort of change for?

**Comment by jillr** [comment]
@pabelanger Is there any work to be done here or can this be closed?  Does someone from the cloud team need to set jobs up?

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
@jillr @goneri @abikouo: network-ee jobs are working properly on amazon.aws, if we want to fill back to them

**Pull request closed without merging**
