### PR TITLE
[PR #347 backport][stable-1.5] remove references to shippable from repo

### PR DESCRIPTION
**Pull request by tremble**
**This is a partial backport of PR #347 as merged into main (bcba66940009da50e5c3585ecb7190b7d5323a19).**

##### SUMMARY

This collection has been operating on Zuul CI for some weeks now

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
shippable.yml
tests/
README.md

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
I've removed some of the flaky tests so we can push this through piecemeal

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by jillr — APPROVED** [review]

**Pull request merged**
