### PR TITLE
Prep amazon.aws 7.4.0

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Prep amazon.aws 7.4.0
Release date is March 5th.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

several

### CODE REVIEW

**Review by GomathiselviS — APPROVED** [review]

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by tremble** [comment]
Test failure appears to be an "eventual consistency" issue.

**Pull request merged**
