### PR TITLE
Remove deprecated "facts" aliases

### PR DESCRIPTION
**Pull request by jillr**
##### SUMMARY

Modules named "facts.py" that do not return ansible_facts were renamed to "info.py" in 2.9. Remove these aliases now that the deprecation period is over.

This PR should be included in 3.0.0 of the collection.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
*_facts.py

##### ADDITIONAL INFORMATION
aws_az_facts.py has a deprecation date of 2022-06, so has not been removed.

### CODE REVIEW

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by jillr** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by jillr** [comment]
so many test flakes :sob:

**Comment by jillr** [comment]
I cant reproduce these test failures locally, they're different failed tests nearly every time, and it passed check.  It's flakes so we're going to have to just keep trying I guess?

**Pull request merged**
