### PR TITLE
delete 'get_classic_link_status' method

### LINKED ISSUE #1114: [6.0.0] Drop support for EC2 Classic networking
### Summary

[Amazon announced that they're dropping support for "EC2 Classic" (non-VPC networking) in July 2021](https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/).  This is sometimes referred to as "Classic-Link"

Specifically stating that:
> On August 15, 2022 [Amazon AWS] expect all migrations to be complete, with no remaining EC2-Classic resources present in any AWS account.

We're now past that date, it's reasonable to start dropping support for EC2-Classic for 6.0.0.  Anyone who's got an exception from Amazon to continue to support EC2 Classic will still be able to use our 5.x releases.

### Issue Type

Feature Idea

### Component Name

(Known examples)
plugins/modules/ec2_eip.py (`in_vpc` parameter - `Domain` when passed to boto3 should now always be `vpc`)
plugins/modules/ec2_vpc_net.py
plugins/modules/ec2_security_group.py
plugins/module_utils/botocore.py
plugins/lookup/aws_account_attribute.py  (see also #1092)

### Additional Information

**Note**: This does _NOT_ include Classic ELBs which _are_ still supported.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by deronnax**
##### SUMMARY

fixes #1114 

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
ec2_vpc_net

##### ADDITIONAL INFORMATION
I picked the issue to get started into contributing to ansible because it was easy to fix, if I did something wrong just tell and I will get it fixed and improved until the PR eventually passes all checks and get merged.

### CODE REVIEW

**Comment by tremble** [comment]
Thanks for taking the time to open this PR.

2 things
1) Please add a changelog fragment (https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to)
2) Please update the integration tests (tests/integration/targets/ec2_vpc_net/tasks/main.yml)

**Comment by tremble** [comment]
(Please ignore the "RETRY_LIMIT" errors, there was a recent update to the environment which is causing random tests to fail to start)

**Comment by tremble** [comment]
recheck

**Review by tremble — APPROVED** [review]

**Comment by deronnax** [comment]
Hello Mark. 
I am really sorry I did not come back to it before you did, I have been very busy with job interviews.
Thank you very much for finishing the job.

**Pull request merged**
