### PR TITLE
[manual backport stable-5] Pick up app_callback -> set_password rather than app_callback -> set_passwd

### PR DESCRIPTION
**Pull request by alinabuzachis**
Pick up app_callback -> set_password rather than app_callback -> set_passwd

SUMMARY

Closes: #1449
Pick up app_callback -> set_password rather than app_callback -> set_passwd

ISSUE TYPE

Bugfix Pull Request
Docs Pull Request
Feature Pull Request
New Module Pull Request

COMPONENT NAME

ADDITIONAL INFORMATION

Reviewed-by: Mark Chappell

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by tremble** [comment]
regate

**Comment by alinabuzachis** [comment]
This one is weird. Tests succeed here https://github.com/ansible-collections/amazon.aws/pull/1507 while they fail in this PR. @tremble

**Comment by alinabuzachis** [comment]
Oh, wait! This seems happening on stable-5 only!

**Comment by tremble** [comment]
> Oh, wait! This seems happening on stable-5 only!

Yeah, and I can't reproduce this either

**Comment by alinabuzachis** [comment]
@tremble 

It seems the ip address and subnet_b_startswith do not match

```
TASK [ec2_instance_tags_and_vpc_settings : debug] ******************************
--
3856 | 2023-05-03 14:45:35.012580 \| controller \| task path: /home/zuul-worker/.ansible/collections/ansible_collections/amazon/aws/tests/integration/targets/ec2_instance_tags_and_vpc_settings/tasks/main.yml:135
3857 | 2023-05-03 14:45:35.064488 \| controller \| ok: [testhost] => {
3858 | 2023-05-03 14:45:35.064524 \| controller \|     "check_tags.instances[0].private_ip_address": "10.86.33.135"
3859 | 2023-05-03 14:45:35.064530 \| controller \| }
3860 | 2023-05-03 14:45:35.064535 \| controller \|
3861 | 2023-05-03 14:45:35.064540 \| controller \| TASK [ec2_instance_tags_and_vpc_settings : debug] ******************************
3862 | 2023-05-03 14:45:35.064545 \| controller \| task path: /home/zuul-worker/.ansible/collections/ansible_collections/amazon/aws/tests/integration/targets/ec2_instance_tags_and_vpc_settings/tasks/main.yml:138
3863 | 2023-05-03 14:45:35.112891 \| controller \| ok: [testhost] => {
3864 | 2023-05-03 14:45:35.112927 \| controller \|     "testing_subnet_b": {
3865 | 2023-05-03 14:45:35.112933 \| controller \|         "changed": true,
3866 | 2023-05-03 14:45:35.112938 \| controller \|         "deprecations": [
3867 | 2023-05-03 14:45:35.112942 \| controller \|             {
3868 | 2023-05-03 14:45:35.112947 \| controller \|                 "collection_name": "amazon.aws",
3869 | 2023-05-03 14:45:35.112953 \| controller \|                 "date": "2024-12-01",
3870 | 2023-05-03 14:45:35.112959 \| controller \|                 "msg": "Alias 'security_token' is deprecated. See the module docs for more information"
3871 | 2023-05-03 14:45:35.112964 \| controller \|             }
3872 | 2023-05-03 14:45:35.112969 \| controller \|         ],
3873 | 2023-05-03 14:45:35.112973 \| controller \|         "failed": false,
3874 | 2023-05-03 14:45:35.112978 \| controller \|         "resource_actions": [
3875 | 2023-05-03 14:45:35.112983 \| controller \|             "ec2:CreateTags",
3876 | 2023-05-03 14:45:35.112987 \| controller \|             "ec2:DescribeTags",
3877 | 2023-05-03 14:45:35.113003 \| controller \|             "ec2:DescribeSubnets",
3878 | 2023-05-03 14:45:35.113010 \| controller \|             "ec2:CreateSubnet"
3879 | 2023-05-03 14:45:35.113015 \| controller \|         ],
3880 | 2023-05-03 14:45:35.113020 \| controller \|         "subnet": {
3881 | 2023-05-03 14:45:35.113024 \| controller \|             "assign_ipv6_address_on_creation": false,
3882 | 2023-05-03 14:45:35.113029 \| controller \|             "availability_zone": "us-east-1b",
3883 | 2023-05-03 14:45:35.113034 \| controller \|             "availability_zone_id": "use1-az4",
3884 | 2023-05-03 14:45:35.113039 \| controller \|             "available_ip_address_count": 251,
3885 | 2023-05-03 14:45:35.113043 \| controller \|             "cidr_block": "10.86.33.0/24",
3886 | 2023-05-03 14:45:35.113050 \| controller \|             "default_for_az": false,
3887 | 2023-05-03 14:45:35.113054 \| controller \|             "id": "subnet-04b068971c8a7000d",
3888 | 2023-05-03 14:45:35.113059 \| controller \|             "ipv6_association_id": "",
3889 | 2023-05-03 14:45:35.113064 \| controller \|             "ipv6_cidr_block": "",
3890 | 2023-05-03 14:45:35.113069 \| controller \|             "ipv6_cidr_block_association_set": [],
3891 | 2023-05-03 14:45:35.113074 \| controller \|             "map_customer_owned_ip_on_launch": false,
3892 | 2023-05-03 14:45:35.113079 \| controller \|             "map_public_ip_on_launch": false,
3893 | 2023-05-03 14:45:35.113083 \| controller \|             "owner_id": "966509639900",
3894 | 2023-05-03 14:45:35.113088 \| controller \|             "state": "available",
3895 | 2023-05-03 14:45:35.113093 \| controller \|             "subnet_arn": "arn:aws:ec2:us-east-1:966509639900:subnet/subnet-04b068971c8a7000d",
3896 | 2023-05-03 14:45:35.113099 \| controller \|             "tags": {
3897 | 2023-05-03 14:45:35.113104 \| controller \|                 "Name": "ansible-test-24979636-ip-172-16-39-140-subnet-b"
3898 | 2023-05-03 14:45:35.113109 \| controller \|             },
3899 | 2023-05-03 14:45:35.113114 \| controller \|             "vpc_id": "vpc-08f075a688b2b4916"
3900 | 2023-05-03 14:45:35.113119 \| controller \|         }
3901 | 2023-05-03 14:45:35.113124 \| controller \|     }
3902 | 2023-05-03 14:45:35.113129 \| controller \| }
3903 | 2023-05-03 14:45:35.113135 \| controller \|
3904 | 2023-05-03 14:45:35.113140 \| controller \| TASK [ec2_instance_tags_and_vpc_settings : debug] ******************************
3905 | 2023-05-03 14:45:35.113146 \| controller \| task path: /home/zuul-worker/.ansible/collections/ansible_collections/amazon/aws/tests/integration/targets/ec2_instance_tags_and_vpc_settings/tasks/main.yml:141
3906 | 2023-05-03 14:45:35.157794 \| controller \| ok: [testhost] => {
3907 | 2023-05-03 14:45:35.157830 \| controller \|     "subnet_b_startswith": "10.76.33."
3908 | 2023-05-03 14:45:35.157836 \| controller \| }
3909 | 2023-05-03 14:45:35.157841 \| controller \|

```

**Comment by tremble** [comment]
@alinabuzachis I've tried pulling in #1259...

**Comment by alinabuzachis** [comment]
> @alinabuzachis I've tried pulling in #1259...

Yeah, it seems the backport for that PR didn't have at that time. Hopefully it fixes

**Pull request merged**
