### PR TITLE
rework s3_bucket and ec2_instance tests to make sure they have the right botocore available for tests needing recent botocore

### PR DESCRIPTION
**Pull request by tremble**
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

s3_bucket
ec2_instance

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
First attempt at gating failed due to problems with CI itself.

**Pull request merged**
