### PR TITLE
DNM Try cross-repo testing rds

### PR DESCRIPTION
**Pull request by alinabuzachis**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1357

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@goneri It cannot run tests because of this 

```
RLIMIT_NOFILE: (1024, 524288)
MAXFD: -1
Falling back to tests in "tests/integration/targets/" because "roles/test/" was not found.
ERROR: Target pattern not matched: rds_instance
```

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
@alinabuzachis it looks better this time ^^.

**Comment by goneri** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
recheck

**Pull request closed without merging**
