### PR TITLE
DNM Promote ec2_transit_gateway_vpc_attachment and ec2_transit_gateway_vpc_attachment_info modules and tests

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Promote ec2_transit_gateway_vpc_attachment and ec2_transit_gateway_vpc_attachment_info modules and tests

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by mandar242 — APPROVED** [review]

**Comment by mandar242** [comment]
rebase required

**Pull request merged**
