### PR TITLE
feat: add mq inventory plugin; addresses #1571

### PR DESCRIPTION
**Pull request by alialkhalidi**
##### SUMMARY
MQ broker inventory source

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
aws_mq

##### ADDITIONAL INFORMATION
EXAMPLE USAGE:
```
plugin: aws_mq
regions:
  - ca-central-1
keyed_groups:
  - key: engine_type
    prefix: mq
compose:
  app: 'tags.Applications|split(",")'
hostvars_prefix: aws_
hostvars_suffix: _mq
```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@alialkhalidi Thank you for all the work you're doing. New plugins PRs must be opened against https://github.com/ansible-collections/community.aws. Would you be so kind to open the PR against that repo? I will be very happy to review and help if necessary.

**Comment by alialkhalidi** [comment]
> @alialkhalidi Thank you for all the work you're doing. New plugins PRs must be opened against https://github.com/ansible-collections/community.aws. Would you be so kind to open the PR against that repo? I will be very happy to review and help if necessary.

@alinabuzachis thank you, and appreciate your help pointing me in the right direction, but may be I'm missing something here. what would the PR against community.aws PR have? the work is for an inventory plugin, and those exist only in amazon.aws repo, no?

**Comment by alialkhalidi** [comment]
failing due to ci permissions:

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": true,
    "cmd": [
        "aws",
        "mq",
        "list-brokers"
    ],
    "delta": "0:00:00.570712",
    "end": "2023-05-27 12:03:06.682023",
    "invocation": {
        "module_args": {
            "_raw_params": "aws mq  list-brokers\n",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true
        }
    },
    "msg": "non-zero return code",
    "rc": 255,
    "start": "2023-05-27 12:03:06.111311",
    "stderr": "\nAn error occurred (AccessDeniedException) when calling the ListBrokers operation: User: arn:aws:sts::966509639900:assumed-role/ansible-core-ci-test-prod/prod=remote=zuul-cloud is not authorized to perform: mq:ListBrokers on resource: arn:aws:mq:us-east-1:966509639900:*",
    "stderr_lines": [
        "",
        "An error occurred (AccessDeniedException) when calling the ListBrokers operation: User: arn:aws:sts::966509639900:assumed-role/ansible-core-ci-test-prod/prod=remote=zuul-cloud is not authorized to perform: mq:ListBrokers on resource: arn:aws:mq:us-east-1:966509639900:*"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

corresponding permission PR: https://github.com/mattclay/aws-terminator/pull/282


ready_for_review

**Comment by alialkhalidi** [comment]
closing, and continuing in: https://github.com/ansible-collections/community.aws/pull/1831

**Pull request closed without merging**
