### PR TITLE
Integration test dependency cleanup

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

- remove dependencies on setup_remote_tmp_dir where it's not used (often just copy & paste from another test)
- remove setup_ec2 (no main.yml means it's not doing anything)
- remove prepare_tests (empty main.yml means it's not doing anything)

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

tests/integration/targets

##### ADDITIONAL INFORMATION

By cleaning up what we have we reduce the chance of people copying things about "because that's what test XYZ did".

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Review by markuman — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by goneri** [comment]
regate

**Comment by tremble** [comment]
regate

**Pull request merged**
