### PR TITLE
fix public_access example

### PR DESCRIPTION
**Pull request by jam01**
##### SUMMARY

Fixes amazon.aws.s3_bucket pubilc_access examples in documentation

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

amazon.aws.s3_bucket

### CODE REVIEW

**Review by tremble — CHANGES_REQUESTED** [review]
Hi @jam01 

Thanks for taking the time to raise this PR.  This certainly looks like the correct update to the docs.

The docs are automatically generated from the module (https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/s3_bucket.py#L189) please could you update it there too or it'll be reverted the next time we perform a release.

**Comment by jam01** [comment]
Done! @tremble thanks for taking a look

**Review by tremble — APPROVED** [review]
Thanks

**Comment by tremble** [comment]
Test failure was galaxy related rather than due to this PR

**Comment by tremble** [comment]
@jam01 thanks for your submission.  Due to the way the docs are generated it'll be a little while before these are on the Ansible website, but they will get there...

**Comment by jam01** [comment]
Ah ok, understood.

**Pull request merged**
