### PR TITLE
Grab logic from the lambda module so that we can get partition (aws, aws-cn, aws-us-gov, etc)

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Adds module_utils.iam.get_account_info which also returns the partition.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/module_utils/iam.py

##### ADDITIONAL INFORMATION

Will follow up with a quick test suite.

### CODE REVIEW

**Comment by jillr** [comment]
@tremble For clarity, is this WIP pending the test suite?  It would be nice to have unit test coverage for this functionality as we can't integration test against govcloud or CN.

**Comment by tremble** [comment]
@jillr I was in two minds about getting the test cases in first since mocking boto pieces is a PITA.  Given it's a module_utils change I really should.  I'll drop this into WIP.

**Review by jillr — APPROVED** [review]
LGTM when the merge conflict is resolved - thanks for this!

**Comment by tremble** [comment]
Rebase complete.  Merging on the basis of @jillr's LGTM.

**Pull request merged**
