### PR TITLE
Mass remove Python 2.x compatibility code

### PR DESCRIPTION
**Pull request by tremble**
Depends-On: https://github.com/ansible-collections/amazon.aws/pull/1259

##### SUMMARY

We dropped support for Python < 3.6 in release 2.0, and ansible-test now respects this and doesn't complain about the missing compatibility code, so drop the extra code

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/
tests/unit/

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Review by alinabuzachis — COMMENTED** [review]
LGTM so far.

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
@alinabuzachis @goneri I think this one's good to merge now, there's 4 changes

- drop the boiler-plate imports
- use super()
- drop the `(object)` when defining classes which just inherit from object (this is automatic)
- droped some unused helpers from tests/unit

**Review by goneri — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Pull request merged**
