### PR TITLE
Fix sanity workflow

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Fix sanity workflow

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by tremble — CHANGES_REQUESTED** [review]
Done this way we continue to apply devel/milestone tests to a bugfix-only branch, which I don't think is the right approach.

The approach from https://github.com/ansible-collections/community.aws/pull/2000 might be better.  Lock to the versions from just after 7.0.0's release, and drop devel/milestone.

**Comment by gravesm** [comment]
> Done this way we continue to apply devel/milestone tests to a bugfix-only branch, which I don't think is the right approach.
> 
> The approach from [ansible-collections/community.aws#2000](https://github.com/ansible-collections/community.aws/pull/2000) might be better. Lock to the versions from just after 7.0.0's release, and drop devel/milestone.

I agree this is a more reasonable approach, but I'm not sure if our downstream publishing pipeline will support this. If we are still releasing off the stable-6 branch when ansible 2.17 is released, it will still have to pass sanity tests on 2.17 before being published downstream.

In the interest of getting the 6.x release out, I'm fine with either approach for now, but we may need to revisit this.

**Comment by tremble** [comment]
> I agree this is a more reasonable approach, but I'm not sure if our downstream publishing pipeline will support this. If we are still releasing off the stable-6 branch when ansible 2.17 is released, it will still have to pass sanity tests on 2.17 before being published downstream.

We've been releasing on a cadence that has our next major version available with the next major version of Ansible.  As such I would expect us to be releasing 7.0.0 and dropping stable-6 at about the same time Ansible collections 10 enters the feature  freeze.

**Comment by tremble** [comment]
recheck

**Review by tremble — APPROVED** [review]

**Comment by alinabuzachis** [comment]
regate

**Comment by tremble** [comment]
Manual merge (touches .github directory)

**Pull request merged**
