### PR TITLE
Add "Darker" github action

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

- Adds a "Darker" github action which picks up on black linting issues for the sections of a file which have changed.
- Adds a pyproject.toml for default black/darker configuration 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

.github/workflows

### CODE REVIEW

**Comment by tremble** [comment]
An example of this running can be found in https://github.com/tremble/amazon.aws/actions/runs/4223007317/jobs/7332206563

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by jillr — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
90% sure this was failing to merge because of the .github/workflows change

**Pull request merged**
