### PR TITLE
ec2_metadata_facts - tests - Wait for instance to reach running state before trying to SSH into it.

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

ec2_metadata_facts has been flaking since the ec2_instance change - make sure we wait for the instance to reach "running" and for SSH to be accepting connections  before we start trying to SSH into it.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_metadata_facts

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Review by jillr — APPROVED** [review]

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
I kicked these tests off locally against the CI account with increasing extra pauses.  Smashing refresh on the console the instance was genuinely `pending` for 8.5 - 11 minutes before reaching `running` and  InstanceReachability checks never succeeded.  One never came out of `pending` at 14 minutes.  AWS Status page says EC2 in us-east-1 is green, lol.  Maybe we'll have better luck tomorrow?

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
