### PR TITLE
Bulk header cleanup

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY
Based upon:

https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#python-shebang-utf-8-coding
> Begin your Ansible module with `#!/usr/bin/python` - this “shebang” allows ansible_python_interpreter to work. Follow the shebang immediately with `# -*- coding: utf-8 -*-` to clarify that the file is UTF-8 encoded.

and
https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#copyright-and-license
>  After the shebang and UTF-8 coding, add a [copyright line](https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/) with the original copyright holder and a license declaration. The license declaration should be ONLY one line, not the full GPL prefix.
...
> Additions to the module (for instance, rewrites) are not permitted to add additional copyright lines other than the default copyright statement if missing:

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

<various>

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
@jillr @alinabuzachis 

Because this PR touches module_utils it's basically triggering every single test.  Without "retry_failed" and with Zuul itself being flaky (RETRY_LIMIT), this is really painful to gate.

How do you feel about temporarily disabling the branch protection and manually merging?

**Comment by tremble** [comment]
regate

**Review by jillr — APPROVED** [review]

**Comment by jillr** [comment]
This PR does not change any code or functionality, but runs many tests because of the number of files it touches which is causing timeouts.  When the gate job that is currently running inevitability times out I will manually merge.

**Pull request merged**
