### PR TITLE
Add Collection Docs workflow to generate docs artifacts

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Generate diffs and artefacts when someone pushes a docs PR

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

.github/workflow

##### ADDITIONAL INFORMATION

Suggested by felixfontein on #787 

Example run: https://github.com/tremble/amazon.aws/actions/runs/2238465237

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @briantist

**Comment by felixfontein** [comment]
Looks good to me. (Even though that's not what I was suggested, but this is also great :D )

I guess you have to merge this so that the action actually runs. It did however ran in @tremble's repo: https://github.com/tremble/amazon.aws/runs/6173432175?check_suite_focus=true The problem seems to be an undefined label `ansible_tower` in guide_aws.rst (line 241).

**Comment by felixfontein** [comment]
The reason this doesn't work is probably due to intersphinx not working. The reference does work on devel, but redirects to the Ansible 3 docs: https://docs.ansible.com/ansible/devel/collections/amazon/aws/docsite/guide_aws.html#autoscaling-with-ansible-tower

I guess this reference should be avoided. Better link to the Tower product page or something like that :)

**Comment by tremble** [comment]
I'm switching this to a "WIP" as merging will currently break things due to the broken link in the docs.  I don't intend to change this PR (the PR worked, the docs are broken), instead I'll have some separate PRs for fixing and updating the guides/docs

**Comment by briantist** [comment]
> I'm switching this to a "WIP" as merging will currently break things due to the broken link in the docs. I don't intend to change this PR (the PR worked, the docs are broken), instead I'll have some separate PRs for fixing and updating the guides/docs

I think this is the right move, in fact I might make it _more_ strict by having it fail on errors.

Since this PR is adding PR docs build, I would add another job that runs parallel to the build, like we've done on `lowlydba.sqlserver`:
https://github.com/lowlydba/lowlydba.sqlserver/blob/main/.github/workflows/docs-pr.yml

This runs a separate build (validate) with the _most strict_ options (fail the CI on any problem), while the build that produces an artifact (and could be published) is produced with the _most lenient_ options, giving the best chance of producing rendered docs you can look at, even if they have some errors.

This PR doesn't seem to be adding a build on push, but that's a good one to have too. It would look like this (a little simpler), but you can remove the publishing step:
https://github.com/ansible-collections/community.hashi_vault/blob/main/.github/workflows/docs-push.yml

**Comment by briantist** [comment]
The extra validate job is something I want to incorporate into the PR shared workflow so it will not need to be added manually:
https://github.com/ansible-community/github-docs-build/issues/33

It's also fine to leave this PR as is, and get a validate job automatically when the shared workflow is updated.

**Comment by tremble** [comment]
@felixfontein @briantist - Any idea how to solve:
```
  /home/runner/work/_temp/docsbuild/rst/collections/amazon/aws/aws_s3_module.rst:1478: WARNING: Duplicate explicit target name: "ansible_collections.amazon.aws.aws_s3_module__parameter-s3_url".
  /home/runner/work/_temp/docsbuild/rst/collections/amazon/aws/s3_bucket_module.rst:1148: WARNING: Duplicate explicit target name: "ansible_collections.amazon.aws.s3_bucket_module__parameter-s3_url".
```

It's caused by a module having 'S3_URL' as an alias for the 's3_url' parameter.  This feels like it's actually a bug in antsibull-docs ?

**Comment by briantist** [comment]
> @felixfontein @briantist - Any idea how to solve:
> 
> ```
>   /home/runner/work/_temp/docsbuild/rst/collections/amazon/aws/aws_s3_module.rst:1478: WARNING: Duplicate explicit target name: "ansible_collections.amazon.aws.aws_s3_module__parameter-s3_url".
>   /home/runner/work/_temp/docsbuild/rst/collections/amazon/aws/s3_bucket_module.rst:1148: WARNING: Duplicate explicit target name: "ansible_collections.amazon.aws.s3_bucket_module__parameter-s3_url".
> ```
> 
> It's caused by a module having 'S3_URL' as an alias for the 's3_url' parameter. This feels like it's actually a bug in antsibull-docs ?

This one is addressed by:
- https://github.com/ansible-community/antsibull-docs/pull/7

It looks like that will probably get merged/released in a relatively short amount of time, but if you want to work around it, use the `lenient` option for the docs build stuff.

**Comment by tremble** [comment]
And with doc fixups (#796 #792) merged main is now in a good state.

@jillr @alinabuzachis how do you feel about enabling this.  From my testing, unless we backport this, the workflow won't trigger on the stable- branches.  But I think this is actually ok since the testing should have happened in main prior to anything being backported.

**Review by briantist — APPROVED** [review]
> From my testing, unless we backport this, the workflow won't trigger on the stable- branches. But I think this is actually ok since the testing should have happened in main prior to anything being backported.

I guess there's two ways to look at it: if you want to eventually publish separate documentation for the other stable branches (not on docs.ansible.com), it should be backported. My collection doesn't use stable branches but I do publish docs for the `main` branch for example, so that they are available somewhere.

I am working on a shared workflow for publishing to GitHub pages; there's already one to publish to surge.sh which is what I use on my collection currently.

You also don't have to wait for me and can implement your own publishing at any time.

Anyway all that can be revisited after working with it on `main` first I suppose :)

> how do you feel about enabling this

Also I'll point out it's very easy to disable even temporarily, through the workflow's page in the Actions tab; a commit is not needed to disable/reenable. So it's very low stakes to try!

**Comment by felixfontein** [comment]
I second Brian, this is very easy to deactivate, so I would suggest to add this to `main` and just try it out for some time. If it causes havoc, just disable it, and if it works great, backport it.

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
