### PR TITLE
Add integration test gha workflow

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### SUMMARY

This PR adds integration test workflow for amazon.aws collection.

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
I feel like this work should be synced with https://github.com/ansible-collections/amazon.aws/pull/1391/files.

**Comment by GomathiselviS** [comment]
> I feel like this work should be synced with https://github.com/ansible-collections/amazon.aws/pull/1391/files.

Yes, I will work with @abikouo on this. Hence made this PR a draft and not open for reviews.

**Comment by abikouo** [comment]
> > I feel like this work should be synced with https://github.com/ansible-collections/amazon.aws/pull/1391/files.
> 
> Yes, I will work with @abikouo on this. Hence made this PR a draft and not open for reviews
Integration workflow will be delivered part of this pull request https://github.com/ansible-collections/amazon.aws/pull/1458

**Comment by tremble** [comment]
This PR appears to have been abandoned, as such I'm going to close it.

**Pull request closed without merging**
