### PR TITLE
Prepare 1.5.0 release

### PR DESCRIPTION
**Pull request by jillr**
##### SUMMARY
Run add_docs, generate changelog, and update galaxy.yml for 1.5.0 collection release

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
galaxy.yml

##### ADDITIONAL INFORMATION
This will be the last 1.x release for the collection, bug and security fixes to 1.5.x only going forward

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
note: With the Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/881, we can manually trigger a full CI run.

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
Looking at the test failures, more modules are having problems with the 63 character 'resource_prefix'.  Load balancers have a 32 character limit.

**Comment by goneri** [comment]
> Looking at the test failures, more modules are having problems with the 63 character 'resource_prefix'. Load balancers have a 32 character limit.

Thank you @tremble for the feedback, I will take a look at these errors.

**Comment by goneri** [comment]
recheck

**Review by goneri — APPROVED** [review]

**Pull request merged**
