### PR TITLE
Prepare release 5.4.0

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Release the ~hounds~ collection!

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

CHANGELOG
galaxy.yml

### CODE REVIEW

**Comment by tremble** [comment]
@tomdeblende - This is the first step in releasing 5.4.0

**Comment by tremble** [comment]
Delaying to see if we can get #1437 merged first

**Review by markuman — COMMENTED** [review]
LGTM, but https://github.com/ansible-collections/amazon.aws/pull/1444 must also be included

**Comment by tremble** [comment]
Rebased to include #1437 / #1444

**Review by markuman — APPROVED** [review]

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
