### PR TITLE
Use module_util helper for tagging AMIs

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

We have some helpers for tagging EC2 resources, use them for tagging AMIs.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_ami

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@tremble Does this PR solve this issues https://github.com/ansible-collections/amazon.aws/issues/511 as well?

**Comment by tremble** [comment]
@alinabuzachis It does now, I should probably add an integration test though.

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]
LGTM!

**Pull request merged**
