### PR TITLE
[6.0.0] Bump botocore requirements

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

In line with our botocore version policy bump the minimum requirements

> Starting with the 2.0.0 releases of amazon.aws and community.aws, it is generally the collection's policy to 
> support the versions of botocore and boto3 that were released 12 months prior to the most recent major 
> collection release, following semantic versioning (for example, 2.0.0, 3.0.0).

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/module_utils/botocore.py
requirements.txt

##### ADDITIONAL INFORMATION

Based on a target release date for 6.0.0 of late April I've bumped this to botocore 1.25.0

boto3 - 1.22.0 - "Mon Apr 25 18:07:20 2022 +0000"
botocore - 1.25.0 - "Mon Apr 25 18:07:02 2022 +0000"

### CODE REVIEW

**Comment by tremble** [comment]
Based on a target release data for 6.0.0 of late April I've bumped this to botocore 1.25.0

boto3 - 1.22.0 - "Mon Apr 25 18:07:20 2022 +0000"
botocore - 1.25.0 - "Mon Apr 25 18:07:02 2022 +0000"

**Comment by tremble** [comment]
@alinabuzachis partly as a straw man, I've based these versions off a 'late April' release date for 6.0.0.  How do you feel about aiming for a "late April" release date for 6.0.0.  Cut-off for Ansible-8 inclusion [looks like](https://github.com/ansible/ansible/pull/79598) it'll be mid-May

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
> @alinabuzachis partly as a straw man, I've based these versions off a 'late April' release date for 6.0.0. How do you feel about aiming for a "late April" release date for 6.0.0. Cut-off for Ansible-8 inclusion [looks like](https://github.com/ansible/ansible/pull/79598) it'll be mid-May

I'll discuss with the team and let you know.

**Comment by tremble** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Pull request merged**
