### PR TITLE
Core parameter sanity test cleanup (breaking change)

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Split the sanity cleanup from #287

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/module_utils/core.py

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by tremble** [comment]
@jillr Fixing the `@parameter` linting error necessitates a breaking change (removing the option).  I guess we wait to merge this until the decision about which comes next 1.5 vs 2.0 ?

**Comment by tremble** [comment]
Test failures were known flakes:
- DHCP Options (boto v2)
- connect_to_aws (Amazon getting grumpy due to too multiple failed logins)

**Comment by jillr** [comment]
@tremble Sounds like a plan; we'll need to pick a date (I'm thinking end of month?) to freeze and start landing breaking changes.  the boto3 DHCP refactor can land before this so that CI can go through.

**Comment by tremble** [comment]
End of the month for a 'freeze' WFM.  Maybe we shoot for a 1.5 release at the end of the month (or just after Easter) just so it's available with the current non-breaking changes (since the cost is low), then start landing the 2.0 changes as soon as 1.5 is out.

Don't know if it'd be worth some form of release note that 1.5 is expected to be the last of the v1 releases?

Would we also need to keep a stable-1.5 branch about for older versions of Ansible?  My preference is that for now we wouldn't, or if we did it would be strictly limited to security fixes only.

**Comment by tremble** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Review by jillr — COMMENTED** [review]
devel is now 2.12; this line should also be removed from tests/sanity/ignore-2.12.txt. Looks good after that change.

**Comment by jillr** [comment]
@tremble you fixed the 2.12 file, but now we have merge conflicts. Sorry!  Please feel free to gate this once that is solved!

**Review by jillr — APPROVED** [review]

**Pull request merged**
