### PR TITLE
Adjust booleans from yes/no to true/false

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

As per https://github.com/ansible-community/community-topics/issues/116

See also https://github.com/ansible-collections/community.aws/pull/1420

Closes: #1041 

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

several

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by tremble — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by goneri** [comment]
Hi @alinabuzachis, for the record https://github.com/ansible-collections/amazon.aws/pull/979 addresses the timeout problem.

**Comment by tremble** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Review by abikouo — APPROVED** [review]
LGTM

**Review by goneri — APPROVED** [review]

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
@goneri One of the ec2_instance tests is constantly failing here.

**Comment by goneri** [comment]
Hi @alinabuzachis,

The problem comes from `ec2_vol`, the disk stays with the `attaching` status till the end. `attach_volume()` expects the `attached` volume instead and so it retries to add the volume thus the error.

As far as I understand, `attach_volume()` is supposed to wait till the volume is actually connected:
https://github.com/ansible-collections/amazon.aws/blob/d73b3954f63ae88c4ea9cf64ce5faeaeeb404482/plugins/modules/ec2_vol.py#L554-L555

I'm not sure if it's some sporadic API inconsistency or a recent change somewhere.

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
Regarding the TIMED_OUT errors, it looks the tests are slower than usual. We can try to run less targets in the same jobs if the problem occures too often.

**Comment by goneri** [comment]
```
2022-09-13 16:49:24.097530 | controller | TASK [ec2_instance_instance_multiple : assert] *********************************
2022-09-13 16:49:24.097535 | controller | task path: /home/zuul/.ansible/collections/ansible_collections/amazon/aws/tests/integration/targets/ec2_instance_instance_multiple/tasks/main.yml:163
2022-09-13 16:49:24.153029 | controller | fatal: [testhost]: FAILED! => {
2022-09-13 16:49:24.153068 | controller |     "assertion": "create_multiple_instances is not changed",
2022-09-13 16:49:24.153075 | controller |     "changed": false,
2022-09-13 16:49:24.153081 | controller |     "evaluated_to": false,
2022-09-13 16:49:24.153086 | controller |     "msg": "Assertion failed"
2022-09-13 16:49:24.153090 | controller | }
```

This looks like a similar problem. `Enforce instance count - launch 5 instances` line 55 creates the 5 instances with the status pending. I'm not sure why it doesn't wait.

2022-09-13 16:49:22.761417 | controller |             "state": {
2022-09-13 16:49:22.761423 | controller |                 "code": 0,
2022-09-13 16:49:22.761428 | controller |                 "name": "pending"
2022-09-13 16:49:22.761438 | controller |             },

And so when the `Enforce instance count - launch 5 instances (check_mode - Idempotency)` task comes after, it doesnt see any instance ready and assumes they need to be created.

**Comment by tremble** [comment]
regate

**Comment by goneri** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Pull request merged**
