### PR TITLE
[WIP] ec2_vol: Fix iops setting and enforce iops/throughput parameters usage

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

ec2_vol: Fix iops setting and enforce iops/throughput parameters usage
Fixes: https://github.com/ansible-collections/amazon.aws/issues/330

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_vol
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by markuman** [comment]
ping me for code-review when WIP is done.

**Comment by jillr** [comment]
Thanks for picking this up @markuman 
@alinabuzachis, do we need to keep this WIP open?

**Comment by alinabuzachis** [comment]
@jillr  Thank you. I close it since @markuman opened this PR https://github.com/ansible-collections/amazon.aws/pull/371.

**Pull request closed without merging**
