### PR TITLE
Rework of client creation error handling.

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

breaking_changes:
- module_utils.botocore - ``boto3_conn``'s  ``conn_type`` parameter is now mandatory.

minor_changes:
- module_utils.botocore - the ``boto3_conn`` method now catches ``BotoCoreError`` rather than an incomplete list of subclasses.
- plugin_utils.botocore - the ``boto3_conn`` method now catches ``BotoCoreError`` rather than an incomplete list of subclasses.
- module_utils.modules - replace use of ``botocore.Session`` with ``boto3.Session`` for consistency.

trivial_changes:
- module_utils.botocore - added Type hints.
- plugin_utils.botocore - added Type hints.
- plugin_utils.base - added Type hints.
- module_utils.modules - added Type hints.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

plugins/module_utils/botocore.py
plugins/module_utils/modules.py
plugins/plugin_utils/base.py
plugins/plugin_utils/botocore.py

### CODE REVIEW

**Comment by tremble** [comment]
> Build failed. https://ansible.softwarefactory-project.io/zuul/buildset/d17a6729ddab417f96ff7577a1f8be47
> 
> ❌ [integration-amazon.aws-9 ](https://ansible.softwarefactory-project.io/zuul/build/80f613a0b3d34b558d9922592e7cf6ee) **FAILURE** in 31m 24s 

Lack of Capacity in Region/AZ

> ❌ [integration-community.aws-11 ](https://ansible.softwarefactory-project.io/zuul/build/c06a34efbc934491906f2bcaef7edc0b) **FAILURE** in 43m 58s

Timeout waiting for creation

**Comment by gravesm** [comment]
> Lack of Capacity in Region/AZ

We've seen this a lot more frequently in the past month or two. We put nearly all our instances in one AZ. I don't know if trying to spread them out would help with this or not.

**Comment by tremble** [comment]
> > Lack of Capacity in Region/AZ
> 
> We've seen this a lot more frequently in the past month or two. We put nearly all our instances in one AZ. I don't know if trying to spread them out would help with this or not.

Spreading them out won't really make a massive difference.  It's not really us requesting too many instances, it's Amazon running out of total "t3" capacity in the AZ.  From experience we'll see problems for a while then, once they increase capacity, things will clear up again.  The other option would be trying "t3a.micro" instead "t3.micro".

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Pull request merged**
