### PR TITLE
Revert "Fix on_denied and on_missing bugs (#618) (#747)"

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

This reverts commit 83a9db63d725cab9ce172c611e897db15a90ad0e because it introduces a breaking change that does not need to be included in the current release.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
Once this gets merged I update the prep PR for amazon.aws 3.2.0.

**Review by markuman — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
\o/

**Comment by alinabuzachis** [comment]
> \o/

So, I guess we can merge this? @tremble

**Review by jillr — APPROVED** [review]

**Comment by markuman** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by markuman** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by markuman** [comment]
regate

**Comment by markuman** [comment]
The AWS Test account is running out of capacity @goneri @jillr @ansibullbot 

>     "msg": "Failed to create the VPC: An error occurred (VpcLimitExceeded) when calling the CreateVpc operation: The maximum number of VPCs has been reached.",

**Comment by alinabuzachis** [comment]
regate

**Comment by markuman** [comment]
still no vpc capacity 

>     "msg": "Failed to create the VPC: An error occurred (VpcLimitExceeded) when calling the CreateVpc operation: The maximum number of VPCs has been reached.",

**Comment by alinabuzachis** [comment]
regate

**Comment by goneri** [comment]
regate

**Pull request merged**
