### PR TITLE
Set the back-off delay to 5 minutes before re-deployment

### PR DESCRIPTION
**Pull request by theputta**
##### SUMMARY
backoff_delay parameter is set to 5 minutes before attempting the next retry. This can be useful to avoid immediate repeated API requests in case of throttling.

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Review by tremble — APPROVED** [review]

**Review by tremble — CHANGES_REQUESTED** [review]
Please clean up the whitespace to fix the failing tests.

See for example: https://github.com/ansible-collections/amazon.aws/actions/runs/6872685446/job/18695465378?pr=1856

```
 ERROR: Found 2 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/cloudformation.py:190:25: W291: trailing whitespace
ERROR: plugins/modules/cloudformation.py:191:1: W293: blank line contains whitespace
```

**Comment by theputta** [comment]
> clean up the whitespace to fix the failing tests

done

**Comment by GomathiselviS** [comment]
Hello @theputta, thanks for kickstarting the documentation pull requests. Consolidating all the documentation example-related modifications into a single pull request would be more convenient, rather than having them scattered across multiple PRs. It would be appreciated if you could ensure that all the added examples have been verified. Once you create a single PR with these changes, we will review and validate them on our end. To streamline the process, we plan to close the other PRs, leaving this one open for you to include the changes. Let us know if this approach suits you.

**Comment by GomathiselviS** [comment]
Please rebase the PR.

**Comment by tremble** [comment]
Coming back to this PR: the description of this example is a little misleading.

As the code is written today, the retries only apply to "transient" errors (things like API rate limits).  It won't retry something that simply "failed".  I think it's better not to merge this change.

**Pull request closed without merging**
