### PR TITLE
Drop compile/import tests for old versions of python in sanity tests

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

We don't support Python < 3.6, so drop the tests at the Zuul job level rather than with a large number of !skip entries

##### ISSUE TYPE

- Feature request

##### COMPONENT NAME

sanity tests

##### ADDITIONAL INFORMATION

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1028

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
ansible/ansible-zuul-jobs#1028 now limits the compile/import tests to Python 3.6 and 3.8, and drops the Python 3-ism boilerplate tests, which in turn means we can drop the swathes of "!skip" entries in the ignore files

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
@tremble That's a nice thing in my opinion. BTW, It seems to be an issue with the splitter.

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Pull request merged**
