### PR TITLE
Testing agains 2.11

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

### CODE REVIEW

**Comment by Andersson007** [comment]
Doesn't seem to be related:
```
00:30 fatal: unable to access 'https://opendev.org/openstack/ansible-collections-openstack/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

**Comment by tremble** [comment]
@Andersson007 Some of the failures look to be related.  Looks like we hit the Instance limits during the test.

@jillr can we have more t2.micro please.

**Comment by Andersson007** [comment]
i relaunched all ..more the tests failed this time

**Comment by Andersson007** [comment]
passed, ready for review

**Comment by tremble** [comment]
@jillr I'm of the opinion that while we should test against 2.11, running tests against 2.9, 2.10, 2.11 **and** devel is a little too much (for shippable).  How do you feel about this?

**Comment by goneri** [comment]
We are in the process to switch to Zuul-CI for the AWS collections. I assign this to me to be sure I don't forget to enable the sanity tests with 2.11.

**Comment by tremble** [comment]
Shippable's no longer in use for this collection, closing this PR

**Comment by Andersson007** [comment]
@tremble @goneri cool, thanks! Could we remove the file then?

**Pull request closed without merging**
