### PR TITLE
Fix version_added

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by tremble — APPROVED** [review]
Do we want to make this PR dependent on the backports merging?

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
@tremble Are we good merging it now?

**Comment by tremble** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Review by jillr — APPROVED** [review]
manually merging

**Pull request merged**
