### PR TITLE
Add EKS Fargate Profile waiters

### PR DESCRIPTION
**Pull request by tjarra**
##### SUMMARY

Add waiters for eks fargate profile to manage deleted and created states. 
A PR will be done in community.aws to add a new module to manage the eks_fargate_profile resource that uses these waiters.

New module PR: [ansible-collections/community.aws#942](https://github.com/ansible-collections/community.aws/pull/942)

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

waiter.py

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by tjarra** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
@tjarra Thank you for taking time to work on this. Can you please reference the PR the waiters are needed for?

**Review by jillr — APPROVED** [review]

**Comment by jillr** [comment]
Thanks @tjarra!

**Pull request merged**
