### PR TITLE
Big Black PR

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

In preparation for 6.0.0 we agreed to mass apply the black formatter to our code base.

Hopefully we're only a couple of weeks out now, and we're much more on top of our PRs than we used to be.  This is the big PR...

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/
tests/

##### ADDITIONAL INFORMATION

There are two commits, the first "pre-tunes" a few things so that they're not exploded into lots of extra lines, or squashed into one line.  The second is just the result of `black plugins/ tests`

The integration tests are *highly* likely to fail, because this is going to trigger pretty much everything in amazon.aws and community.aws

### CODE REVIEW

**Review by abikouo — APPROVED** [review]

**Comment by alinabuzachis** [comment]
@tremble 

```
ERROR: Found 4 pylint issue(s) which need to be resolved:
[197](https://github.com/ansible-collections/amazon.aws/actions/runs/4764213866/jobs/8468552897?pr=1465#step:9:198)
ERROR: tests/unit/plugin_utils/connection/test_connection_base.py:34:24: abstract-class-instantiated: Abstract class 'AWSConnectionBase' with abstract methods instantiated
[198](https://github.com/ansible-collections/amazon.aws/actions/runs/4764213866/jobs/8468552897?pr=1465#step:9:199)
ERROR: tests/unit/plugins/modules/test_cloudformation.py:9:0: unused-import: Unused maybe_sleep imported from ansible_collections.amazon.aws.tests.unit.utils.amazon_placebo_fixtures
[199](https://github.com/ansible-collections/amazon.aws/actions/runs/4764213866/jobs/8468552897?pr=1465#step:9:200)
ERROR: tests/unit/plugins/modules/test_cloudformation.py:9:0: unused-import: Unused placeboify imported from ansible_collections.amazon.aws.tests.unit.utils.amazon_placebo_fixtures
[200](https://github.com/ansible-collections/amazon.aws/actions/runs/4764213866/jobs/8468552897?pr=1465#step:9:201)
ERROR: tests/unit/plugins/modules/test_ec2_vpc_dhcp_option.py:9:0: unused-import: Unused placeboify imported from ansible_collections.amazon.aws.tests.unit.utils.amazon_placebo_fixtures
```

**Comment by tremble** [comment]
@alinabuzachis pylint didn't like where black had moved the linting comments.

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Pull request merged**
