### PR TITLE
Remove an unreachable code fragment in ec2_security_group 

### PR DESCRIPTION
**Pull request by openrefactory**
In file: ec2_security_group.py, method: ensure_present, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not have identity and match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. 

I suggested that the logical operation should be done properly.

### CODE REVIEW

**Review by tremble — CHANGES_REQUESTED** [review]
Thanks for taking the time to open this PR.

The description of the PR is a little misleading since the change doesn't remove the code it 'fixes' an accidental bug.

Looking at the integration tests it looks like the expected behaviour (with `purge==True`) now includes purging the default rules, and looking at the history of the module this has been the behaviour since the creation of this collection, with the behaviour being documented as such since the addition of `purge_egress_rules`.

Please update this PR to **remove** the unreachable code.  Additionally, please add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

**Comment by openrefactory** [comment]
@tremble According to your comment, should I remove the entire if block and keep only the else block(of course after removing the else logic)?

**Comment by tremble** [comment]
@openrefactory Yes please

**Comment by openrefactory** [comment]
@tremble  Thanks. I have updated the PR and changes. Please check.

**Review by tremble — APPROVED** [review]
Looks good to me, our CI's currently unavailable due to maintenance.  I'll test & merge once CI's back (assuming the integration tests pass)

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Pull request merged**
