### PR TITLE
tests: split up ec2_instance

### PR DESCRIPTION
**Pull request by goneri**
Use on target per sub-test to have a better control on the global execution
time and simplify the troubleshooting.

### CODE REVIEW

**Review by tremble — CHANGES_REQUESTED** [review]
Most of the tests don't require a new version of botocore/boto3, please prune the use of setup_botocore_pip as this adds a couple of minutes to each test.

Most of the tests don't use the iam roles, I'd avoid coyping `first_iam_role`, `second_iam_role` and `unique_id` around.

Looking at `ec2_instance_find_ami`, I think this should be removed (and should have been removed a while back):  Everything's using `ec2_ami_id` which comes from  `setup_ec2_facts`.

resource_prefix is consistent for a single ansible-test run, this is going to result in identical VPCs being created and (in theory) deleted, please update vpc_name and vpc_seed to be unique per-test.  This helps identify which test is misbehaving when things go wrong and avoid weird edge cases when things go wrong and retries happen.

The new modules aren't deleting the VPCs and subnets they create.  We're only not hitting limits because they're reusing the same VPCs and subnets over and over, this is also going to cause weird failures when aws-terminator happens to clean up at the wrong time.  While the window is small, it's still there and a PITA to debug.  It might be possible to do something clever, using a handler to trigger the cleanup as we do with setup_botocore_pip.  While you're at it I'd probably use the "search based on VPC" trick that we're using for EC2s and ENIs when cleaning up Security Groups and Subnets.

I also have a vague memory that ansible-test won't automatically trigger all of these tests if someone runs this 'locally', but I'll test this...

**Comment by tremble** [comment]
```
(ansible-dev39) 
[10:29:37+0200] ~/vcs/ansible/ansible_collections/amazon/aws  [26372bf|pull/979]
[✔ mchappel@mchappel aws] $ supported_integration -vv ec2_instance
ansible-test integration --docker default --allow-unstable -vv ec2_instance
Configured locale: en_US.UTF-8
RLIMIT_NOFILE: (1024, 262144)
Falling back to tests in "tests/integration/targets/" because "roles/test/" was not found.
FATAL: Target pattern not matched: ec2_instance
Command exited with non-zero status 1
real    0.20s
user    0.18s
sys     0.02s
```

**Review by tremble — APPROVED** [review]

**Comment by goneri** [comment]
Thank you @tremble for the patch.

**Comment by tremble** [comment]
regate

**Pull request merged**
