### PR TITLE
Promote kms_key* modules and tests

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### SUMMARY

Depends-On: https://github.com/ansible/zuul-config/pull/445

Migrate kms_key* module from community.aws

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by tremble — APPROVED** [review]

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Pull request merged**
