### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by AleksaC**

### CODE REVIEW

**Review by tremble — DISMISSED** [review]
Thanks for taking the time to submit this patch.

This RST file is automatically generated from the module as part of the release process.  To avoid a regression the issue needs to be fixed there:

https://github.com/ansible-collections/amazon.aws/blob/main/plugins/inventory/aws_ec2.py#L21

Unfortunately, this actually looks like a bug in the tool we use to generate the RST.  The best option may be to switch it to `C(aws_ec2.{yml|yaml})`

**Comment by AleksaC** [comment]
Oh, didn't see it was generated, sorry. Don't know which tool is used, but it might be intentional and maybe would work by escaping the closing paren. Either way `{yml,yaml}` is probably better anyway.

**Comment by tremble** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Review by jillr — APPROVED** [review]

**Pull request merged**
