### PR TITLE
Prep amazon.aws 7.0.0 release

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Prep amazon.aws 7.0.0 release

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

several

### CODE REVIEW

**Comment by alinabuzachis** [comment]
Closed and re-opened to trigger Github workflows.

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
Realised the failure is probably cause by the lack of stable-7 branch over in community.aws.  If this is the case I'll get a PR in to update the release docs.

**Review by tremble — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by gravesm** [comment]
Seems like a missing stable-7 branch in community.aws wasn't the problem? Not sure what's going on with zuul, but I'm going to go ahead and manually merge this so we ca get the release done.

**Review by hakbailey — APPROVED** [review]

**Pull request merged**
