### PR TITLE
Refactored create_instances in ec2 Module

### PR DESCRIPTION
**Pull request by rkeen9**
##### SUMMARY

As part of a project in a course of software evolution, several refactorings were performed on the create_instances function in the ec2.py module. Key changes are that most variables were inlined, unused variables were removed, and several functions were extracted. All refactorings performed are detailed in each commit.

### CODE REVIEW

**Comment by tremble** [comment]
I've not had chance to fully review this, but from a cursory glance it looks good.

One minor niggle.  You use  `module : Ansible Module object` I don't like this and think that the original `module: AnsibleModule object` is better.  Specifically because AnsibleModule is the **class** of the object, and as such 'Ansible Module' makes it that little bit less accurate.

**Comment by rkeen9** [comment]
@tremble thanks for the  response! I'm away from the computer today but I will work on implementing your feedback tomorrow.

**Comment by rkeen9** [comment]
@tremble I made the change you requested. I also noticed that there were some occurrences of `module: Ansible module` outside of my refactorings so I replaced those with `module: AnsibleModule` in a separate commit.

**Comment by tremble** [comment]
In general the refactors look sane enough and do appear to just be refactoring.

@jillr any thoughts?

**Comment by s-hertel** [comment]
I'm generally not keen about unnecessary editing of this specific module as it tends to break things (and it doesn't have a proper test suite). The refactoring looks nice though.

**Comment by jillr** [comment]
This module is on our list of missing test suites (https://github.com/ansible-collections/amazon.aws/projects/3).  I'm very wary of such a large proactive code change without a test suite, especially for this particular module as it is a complex one with a lot of history.  This PR is a lot of work for which we're very grateful @rkeen9 but I'd want to have comprehensive integration tests landed before I would be comfortable accepting a change like this.

**Pull request closed without merging**
