### PR TITLE
Backport: rds module_util - support IAM roles

### PR DESCRIPTION
**Pull request by jatorcasso**
##### SUMMARY
Backport #714 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
rds

### CODE REVIEW

**Comment by jatorcasso** [comment]
recheck

**Comment by jatorcasso** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by jatorcasso** [comment]
regate

**Comment by jatorcasso** [comment]
regate

**Pull request merged**
