### PR TITLE
DNM Migrate elb_classic_lb_info* modules and tests

### LINKED ISSUE #1863: Add elb_classic_lb_info
### Summary

`elb_classic_lb_info` exists in the community version. In the amazon version there is no way to get info about classic LBs

### Issue Type

Feature Idea

### Component Name

elb_classic_lb

### Additional Information

https://docs.ansible.com/ansible/latest/collections/community/aws/elb_classic_lb_info_module.html

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by mandar242**
Migrate elb_classic_lb_info* modules and tests

remove from community.aws https://github.com/ansible-collections/community.aws/pull/2135

closes #1863

### CODE REVIEW

**Review by GomathiselviS — CHANGES_REQUESTED** [review]
Could you update the integration test to incorporate the fully qualified name? Additionally, please change the reference from `community.aws.elb_classic_lb_info` to `amazon.aws.elb_classic_lb_info` in the tests for `elb_classic_lb`.

**Review by alinabuzachis — COMMENTED** [review]
If you’ve changed something in the module, that needs to be handled in a different PR. The comment was intended for https://github.com/ansible-collections/community.aws/pull/2135

**Comment by tremble** [comment]
@alinabuzachis The updates appear to have been performed in separate commits.  Assuming we perform a non-squash merge I think this is how we handled it in the past.

**Comment by alinabuzachis** [comment]
@tremble I was trying to understand if there was any change to the module’s codebase in this PR. If so, I think we should handle that before doing any promotion. But, I’m not sure if there was any change or not, that’s why I was asking @mandar242.

**Comment by alinabuzachis** [comment]
@tremble However, documentation needs to fixed, especially the RETURN block must be properly documented. 
I would suggest we do that in c.aws first. Any thoughts @tremble?

**Comment by alinabuzachis** [comment]
I was also thinking if it would make sense to refactor a little bit the module to use any of the module_utils for elb (if there are any) or move some of the utils the module uses there.

**Comment by tremble** [comment]
> I was also thinking if it would make sense to refactor a little bit the module to use any of the module_utils for elb (if there are any) or move some of the utils the module uses there.

There's two conflicting things here:
1) We want amazon.aws to be "clean", which would suggest cleaning, then moving
2) We want our commit logs and PR links to be clean, which is easier if we move the modules here, and then clean things up.

Personally I'd lean towards 2, especially if we want to split things into modules_util (cross-repo PRs are a pain to manage).

**Comment by alinabuzachis** [comment]
> > I was also thinking if it would make sense to refactor a little bit the module to use any of the module_utils for elb (if there are any) or move some of the utils the module uses there.
> 
> There's two conflicting things here:
> 
> 1. We want amazon.aws to be "clean", which would suggest cleaning, then moving
> 2. We want our commit logs and PR links to be clean, which is easier if we move the modules here, and then clean things up.
> 
> Personally I'd lean towards 2, especially if we want to split things into modules_util (cross-repo PRs are a pain to manage).

In the past, we've followed the first approach, but I also agree that cross-repo testing is messy. 

I am also good with the second approach since quicker.

The only thing we need to do is to make sure we have a clean module, because we have recently made some efforts (between various refactoring and documentation updates). We should keep those standards.
@mandar242 Can you please:
- Make sure the module's documentation is up to date?
- Refactor the module so that it uses some of the module_utils for elb (if there are any, I didn't check) or move some of the module utilities in the module_utils?
Thanks.

**Comment by mandar242** [comment]
> * module_utils

@alinabuzachis I will take a look. Do these changes need to go in a different PR?
as it would be change to actual code in case "Refactor the module so that it uses some of the module_utils for elb (if there are any, I didn't check) or move some of the module utilities in the module_utils?" is done.

**Comment by mandar242** [comment]
> > > I was also thinking if it would make sense to refactor a little bit the module to use any of the module_utils for elb (if there are any) or move some of the utils the module uses there.
> > 
> > 
> > There's two conflicting things here:
> > 
> > 1. We want amazon.aws to be "clean", which would suggest cleaning, then moving
> > 2. We want our commit logs and PR links to be clean, which is easier if we move the modules here, and then clean things up.
> > 
> > Personally I'd lean towards 2, especially if we want to split things into modules_util (cross-repo PRs are a pain to manage).
> 
> In the past, we've followed the first approach, but I also agree that cross-repo testing is messy.
> 
> I am also good with the second approach since quicker.
> 
> The only thing we need to do is to make sure we have a clean module, because we have recently made some efforts (between various refactoring and documentation updates). We should keep those standards. @mandar242 Can you please:
> 
> * Make sure the module's documentation is up to date?
> * Refactor the module so that it uses some of the module_utils for elb (if there are any, I didn't check) or move some of the module utilities in the module_utils?
>   Thanks.

@alinabuzachis I will take a look. Do these changes need to go in a different PR?
as it would be change to actual code in case "Refactor the module so that it uses some of the module_utils for elb (if there are any, I didn't check) or move some of the module utilities in the module_utils?" is done.

**Comment by mandar242** [comment]
@alinabuzachis as discussed on slack, closing the current migration PRs for elb_classic_lb_info, will work on refactoring the module in c.aws first, will reopen the migration PRs again once refactoring is merged there.
cc @tremble

**Pull request closed without merging**
