### PR TITLE
DNM - Promotion test

### PR DESCRIPTION
**Pull request by goneri**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by goneri** [comment]
Well, I should probably also migrate the tests....

**Comment by tremble** [comment]
I like this approach :)

**Comment by jillr** [comment]
Links back to the community PRs are awesome!

We also need the runtime.yml entries and there are edits that have to happen in some modules for things like when deprecation warnings include the FQCN.  Like this for each module that moves:
```
sed -i 's/community.aws.ec2_vpc_endpoint/amazon.aws.ec2_vpc_endpoint/g' plugins/modules/ec2_vpc_endpoint*
sed -i "s/collection_name='community.aws'/collection_name='amazon.aws'/g" plugins/modules/ec2_vpc_endpoint*
```

**Comment by goneri** [comment]
recheck

**Pull request closed without merging**
