### PR TITLE
Migrate rds_snapshot* modules and tests

### PR DESCRIPTION
**Pull request by alinabuzachis**
Depends-On: https://github.com/ansible/zuul-config/pull/443

Migrate rds_snapshot* modules and tests

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@jillr @tremble Test suite for this module is picked up from rds_instance and rds_cluster aliases files.

**Review by gravesm — APPROVED** [review]

**Comment by abikouo** [comment]
I will add some integration testing once this is merged

**Review by abikouo — APPROVED** [review]

**Review by goneri — APPROVED** [review]

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
regate

**Pull request merged**
