### PR TITLE
Adjust docs publish workflow

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Ref: https://github.com/ansible-community/github-docs-build/issues/92#issuecomment-2198238661

##### ISSUE TYPE
- Docs Pull Request
- Test Pull Request

##### COMPONENT NAME
docs publish on push workflow

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
I guess we would only need to backport to stable-7 and stable-8. @tremble is it correct?

**Comment by felixfontein** [comment]
I added labels for all stable branches that contain these workflows. If some of these branches are fully EOL, it might make sense to remove all CI scripts from these branches (and definitely remove the backport labels here :) ).

**Comment by alinabuzachis** [comment]
@felixfontein Can you please rebase? I would suggest that we merge for now, and then decide what to do with the branches that have reached EOL.

**Comment by felixfontein** [comment]
@alinabuzachis @gravesm thanks for reviewing and merging!

**Pull request merged**
