### PR TITLE
Minor linting fixups - 2022-08-04

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Minor linting fixups
- docs
- unused variables

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/inventory/aws_ec2.py
plugins/inventory/aws_rds.py
plugins/lookup/aws_account_attribute.py
plugins/lookup/aws_secret.py
plugins/lookup/aws_ssm.py
plugins/module_utils/acm.py
plugins/module_utils/botocore.py
plugins/module_utils/cloud.py
plugins/module_utils/iam.py
plugins/module_utils/modules.py
plugins/module_utils/rds.py

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by jillr — APPROVED** [review]

**Review by goneri — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Pull request merged**
