### PR TITLE
Fix CI for the stable-1.5 branch

### PR DESCRIPTION
**Pull request by gravesm**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1361

##### SUMMARY

There are several changes needed to get CI to pass, including:
  * adding the relevant ignores to a 2.13 ignore file
  * adding constraints/requirements for tests
  * removing shippable (there is only zuul)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

CI

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by goneri** [comment]
check ondemand

**Comment by goneri** [comment]
check ondemand

**Comment by alinabuzachis** [comment]
cc @goneri

**Comment by goneri** [comment]
check ondemand

**Comment by gravesm** [comment]
I'm pretty sure the failures at this point are legitimate, and there are changes that will need to be backported. Working now on figuring out what those are.

**Comment by goneri** [comment]
For the ec2_vol error, the instance returns `volume_type: "gp3"` when the test expect `gp2`.

**Comment by goneri** [comment]
To be more specific, we've got a call of:

    - name: change some tag values
      ec2_vol:
        instance: "{{ test_instance.instance_ids[0] }}"
        id: "{{ new_vol_attach_result.volume.id }}"
        device_name: /dev/sdh
        volume_size: 1
        volume_type: gp2
        tags:
          "lowercase spaced": 'hello cruel world ❤️'
          "Title Case": 'Hello Cruel World ❤️'
          CamelCase: 'SimpleCamelCase ❤️'
          snake_case: 'simple_snake_case ❤️'
      register: new_vol_attach_result

And this is enough to change from gp2 to gp3.

**Comment by gravesm** [comment]
check ondemand

**Comment by tremble** [comment]
1.5 is mostly dead at this point, I don't think there's any value in backporting #347 since it's only deleting unused code/aliases but triggers most of the integration tests.  Similarly, there are a number of PRs which would need backporting (in both community.aws and amazon.aws) to properly ensure the boto3/botocore versioning changes.

With #614 and #753 I've added minimal constraints files and the relevant ignore files.  This should be sufficient that we can backport security fixes in the direction of Ansible 2.9 if necessary.

**Pull request closed without merging**
