### PR TITLE
aws_ec2: fix populating SSM inventory for multiple hosts

### LINKED ISSUE #2226: EC2 dynamic inventory SSM inventory collection is broken for environments with more than 40 hosts
### Summary

The function `_get_multiple_ssm_inventories()` in the aforementioned inventory plugin uses the wrong method of updating/merging results from multiple queries.
AWS APIs return a single `Entities` object that contains a list of instance inventory objects. The current result updating method uses `dict.update()`, which overwrites the same `Entities` object on each iteration, instead of updating/merging the results. As a result, we lose inventory for all instances below the x*40 threshold.

### Issue Type

Bug Report

### Component Name

aws_ec2

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.12]
  config file = /Users/janark/Code/host-configuration/ansible.cfg
  configured module search path = ['/Users/janark/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/janark/Code/host-configuration/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/janark/Code/host-configuration/collections:/opt/ansible/collections
  executable location = /Users/janark/Code/host-configuration/venv/bin/ansible
  python version = 3.11.8 (main, Feb 21 2024, 21:11:16) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/Users/janark/Code/host-configuration/venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Collection Versions

```console
$ ansible-galaxy collection list

# /Users/janark/Code/host-configuration/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               8.1.0
ansible.posix                            1.5.4
community.aws                            8.0.0
community.crypto                         2.21.0
community.docker                         3.11.0
community.general                        9.2.0
community.library_inventory_filtering_v1 1.0.1
community.rabbitmq                       1.3.0
```

### AWS SDK versions

```console
$ pip show boto boto3 botocore
WARNING: Package(s) not found: boto
Name: boto3
Version: 1.34.143
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /Users/janark/Code/host-configuration/venv/lib/python3.11/site-packages
Requires: botocore, jmespath, s3transfer
Required-by:
---
Name: botocore
Version: 1.34.143
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /Users/janark/Code/host-configuration/venv/lib/python3.11/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

_No response_

### Steps to Reproduce

Run EC2 inventory discovery against more than 40 hosts.

### Expected Results

SSM inventory (`ssm_inventory`) should be present for all instances that have SSM enabled.

### Actual Results

SSM inventory (`ssm_inventory`) is present only on a select amount of instances.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by r2bit**
##### SUMMARY

The function `_get_ssm_information()` returns dicts with one object. Multiple results cannot be concatenated/merged using `d.update()` since it will keep overwriting one object.
Concatenate the nested lists instead.

Fixes #2226 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

aws_ec2

### CODE REVIEW

**Comment by GomathiselviS** [comment]
Hi @r2bit , Thanks for working on this fix. Can you please add a changelog for this PR?

**Review by abikouo — COMMENTED** [review]
Looks good!! Just missing the changelog.

**Review by abikouo — APPROVED** [review]

**Review by GomathiselviS — APPROVED** [review]
@r2bit Can you rebase the PR? Once done, it can be merged.

**Comment by r2bit** [comment]
> @r2bit Can you rebase the PR? Once done, it can be merged.

@GomathiselviS done.

**Pull request merged**
