### PR TITLE
Remove "missing credentials" tests from ec2_group/ec2_vpc_net

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

AWS Client creation is now done inside a helper module which is more thoroughly tested.  Remove the extra tests from ec2_vpc_net and ec2_group.  They bring no significant value but do bump up the login failure count, which can result in the IPs getting temporarily black-listed

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_group
ec2_vpc_net

##### ADDITIONAL INFORMATION

For more thorough tests look at the module_utils_core tests

### CODE REVIEW

**Review by jillr — APPROVED** [review]
LGTM after 406 lands

**Comment by goneri** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Pull request merged**
