### PR TITLE
Bump version from 7.0.0 to 8.0.0-dev0

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Bump version from 7.0.0 to 8.0.0-dev0

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by tremble — APPROVED** [review]

**Review by hakbailey — APPROVED** [review]

**Comment by abikouo** [comment]
close and reopen to trigger GHA (new commit has been pushed by the bot)

**Review by abikouo — APPROVED** [review]

**Review by tremble — CHANGES_REQUESTED** [review]
We need to add sanity ignore entries and issues for
- the features to be removed in 8.0.0
- the features to be removed after 2023-12-01

**Review by tremble — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by tremble** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Pull request merged**
