### PR TITLE
Remove vendored ipaddress library, we've dropped support for Python < 3.6

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

We've dropped support for Python < 3.6, and we're preparing for a major release.  Drop the vendored version of ipaddress

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/module_utils/compat/_ipaddress.py
plugins/modules/ec2_group.py

##### ADDITIONAL INFORMATION

Depends-On: https://github.com/ansible-collections/amazon.aws/pull/460
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1043
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1055

### CODE REVIEW

**Comment by tremble** [comment]
CC: @felixfontein

**Review by felixfontein — APPROVED** [review]

**Comment by tremble** [comment]
Failed test is fixed by #460

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by pabelanger** [comment]
recheck

**Comment by tremble** [comment]
This work is ready to merge however both myself and @alinabuzachis would like a +1 from @jillr prior to merging this.

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Review by jillr — APPROVED** [review]

**Comment by tremble** [comment]
@pabelanger 34 minutes to gate and a full test-suite run!  Thank-you for your work optimising the AWS jobs.

**Pull request merged**
