### PR TITLE
Clean up a range of small pylint warnings

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Cleans up a range of pylint warnings
- consider-using-dict-items
- assignment-from-no-return
- no-else-continue
- no-else-break
- simplifiable-if-statement
- duplicate-except
- pointless-string-statement
- redefined-outer-name
- redefined-builtin

In the process this also highlighted two bugs which have been fixed
- elb_classic_lb - ``proxy_protocol`` not being set or being set to ``None`` can result in unexpected behaviour or errors ("next" used rather than "continue")
- cloudformation - when fetching stack events automatic retries were only applied when using a filter.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/inventory/aws_ec2.py
plugins/lookup/aws_collection_constants.py
plugins/lookup/aws_service_ip_ranges.py
plugins/lookup/secretsmanager_secret.py
plugins/module_utils/acm.py
plugins/module_utils/modules.py
plugins/modules/autoscaling_group.py
plugins/modules/cloudformation.py
plugins/modules/ec2_eni.py
plugins/modules/ec2_instance.py
plugins/modules/ec2_metadata_facts.py
plugins/modules/ec2_security_group.py
plugins/modules/ec2_vpc_route_table.py
plugins/modules/elb_classic_lb.py
plugins/modules/rds_cluster.py
plugins/modules/rds_instance.py
plugins/modules/rds_param_group.py
plugins/modules/route53_health_check.py
plugins/modules/s3_bucket.py
plugins/modules/s3_object.py
plugins/modules/s3_object_info.py

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@tremble  I see
`ERROR: Found 1 pylint issue(s) which need to be resolved:
ERROR: plugins/module_utils/policy.py:176:4: collection-deprecated-version: Deprecated version ('8.0.0') found in call to Display.deprecated or AnsibleModule.deprecate` on milestone.

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
> @tremble I see `ERROR: Found 1 pylint issue(s) which need to be resolved: ERROR: plugins/module_utils/policy.py:176:4: collection-deprecated-version: Deprecated version ('8.0.0') found in call to Display.deprecated or AnsibleModule.deprecate` on milestone.

Will go away with #2040

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Pull request merged**
