### PR TITLE
Move RetryingBotoClientWrapper into module_utils.retries

### PR DESCRIPTION
**Pull request by tremble**
Depends-On: https://github.com/ansible-collections/community.aws/pull/1579

##### SUMMARY

Move RetryingBotoClientWrapper into module_utils.retries
This means we can use it later with non-module plugins

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/module_utils/modules.py
plugins/module_utils/retries.py
plugins/module_utils/waiters.py

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by goneri — APPROVED** [review]

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
@goneri ec2_snapshot tests already failing again :/

**Comment by goneri** [comment]
> @goneri ec2_snapshot tests already failing again :/

Please, don't disable it. I would like to make it work.

**Pull request merged**
